dependencies:
- name: kubernetes-dashboard
  version: 0.7.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: nginx-ingress
  version: 0.22.1
  repository: https://kubernetes-charts.storage.googleapis.com
