apiVersion: v1
kind: Service
metadata:
  name: {{ include "ct-carbon-relay.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "ct-carbon-relay.name" . }}
    app: {{ include "ct-carbon-relay.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.labels}}
    {{ $key }}: {{ $value }}
    {{- end}}
  annotations:
    {{- range $key, $value := .Values.elbAnnotations}}
    {{ $key }}: {{ $value }}
    {{- end}}
spec:
  ports:
  - name: graphite
    port: 2003
    targetPort: 2003
  - name: http
    port: 8081
    targetPort: 8081    
  selector:
    app: {{ include "ct-carbon-relay.name" . }}
    release: {{ .Release.Name }}
  type: LoadBalancer

