# Default values for ct-acme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

route53:
  region: us-west-2
  hostedZoneId:

acme:
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  email:
